// MongoDB insertion query for 50 prediction market questions

// MongoDB insertion query for 50 prediction market questions

const { MongoClient } = require('mongodb');


const marketData = [
    {
      title: "Will Bitcoin reach $100,000 by the end of 2025?",
      description: "This market resolves to YES if the price of Bitcoin reaches or exceeds $100,000 USD on any major exchange before January 1, 2026.",
      probability: 65,
      volume: "$15,000",
      endDate: "2025-12-31",
      category: "Crypto",
      isResolved: false,
      change: 3,
      traders: 87,
      resolutionDetails: "Resolution will be based on the closing price on Coinbase, Binance, and Kraken. At least two of these exchanges must show BTC at $100,000 or higher.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India win the 2025 Cricket World Cup?",
      description: "This market resolves to YES if the Indian cricket team wins the 2025 ICC Cricket World Cup.",
      probability: 42,
      volume: "$8,500",
      endDate: "2025-11-30",
      category: "Sports",
      isResolved: false,
      change: -2,
      traders: 156,
      resolutionDetails: "Resolution will be based on the official results as declared by the International Cricket Council (ICC).",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Ethereum transition to Ethereum 3.0 by Q3 2025?",
      description: "This market resolves to YES if Ethereum successfully implements and transitions to Ethereum 3.0 by September 30, 2025.",
      probability: 38,
      volume: "$7,200",
      endDate: "2025-09-30",
      category: "Crypto",
      isResolved: false,
      change: 5,
      traders: 64,
      resolutionDetails: "Resolution will be based on official announcements from the Ethereum Foundation and successful implementation on the mainnet.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will SpaceX successfully land humans on Mars by 2026?",
      description: "This market resolves to YES if SpaceX successfully lands at least one human on the surface of Mars by December 31, 2026.",
      probability: 15,
      volume: "$12,300",
      endDate: "2026-12-31",
      category: "Science",
      isResolved: false,
      change: -1,
      traders: 203,
      resolutionDetails: "Resolution will be based on official confirmation from SpaceX and independent verification from NASA or other space agencies.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will inflation in India drop below 4% in 2025?",
      description: "This market resolves to YES if the annual inflation rate in India, as measured by the Consumer Price Index (CPI), falls below 4% for at least two consecutive quarters in 2025.",
      probability: 55,
      volume: "$5,800",
      endDate: "2025-12-31",
      category: "Economics",
      isResolved: false,
      change: 2,
      traders: 78,
      resolutionDetails: "Resolution will be based on official inflation data published by the Reserve Bank of India (RBI).",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Narendra Modi remain Prime Minister after the 2024 general elections?",
      description: "This market resolves to YES if Narendra Modi continues to serve as the Prime Minister of India after the 2024 general elections.",
      probability: 72,
      volume: "$18,500",
      endDate: "2024-06-30",
      category: "Politics",
      isResolved: false,
      change: 4,
      traders: 312,
      resolutionDetails: "Resolution will be based on the official election results and government formation as announced by the Election Commission of India.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will 'Kalki 2898 AD' become the highest-grossing Indian film of all time?",
      description: "This market resolves to YES if 'Kalki 2898 AD' surpasses the current highest-grossing Indian film of all time in worldwide box office collections.",
      probability: 48,
      volume: "$6,200",
      endDate: "2024-12-31",
      category: "Entertainment",
      isResolved: false,
      change: 8,
      traders: 94,
      resolutionDetails: "Resolution will be based on verified box office reports from trusted industry sources like Box Office India and Box Office Mojo.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will the RBI launch a digital rupee for retail use by end of 2024?",
      description: "This market resolves to YES if the Reserve Bank of India officially launches a Central Bank Digital Currency (CBDC) for retail use by December 31, 2024.",
      probability: 63,
      volume: "$4,800",
      endDate: "2024-12-31",
      category: "Economics",
      isResolved: false,
      change: 5,
      traders: 67,
      resolutionDetails: "Resolution will be based on official announcements and implementation by the Reserve Bank of India.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India win more than 10 gold medals at the 2024 Olympics?",
      description: "This market resolves to YES if India wins more than 10 gold medals at the 2024 Summer Olympics in Paris.",
      probability: 25,
      volume: "$7,500",
      endDate: "2024-08-11",
      category: "Sports",
      isResolved: false,
      change: 3,
      traders: 128,
      resolutionDetails: "Resolution will be based on the official medal count as declared by the International Olympic Committee at the conclusion of the 2024 Summer Olympics.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Solana overtake Ethereum in daily transactions by end of 2025?",
      description: "This market resolves to YES if Solana consistently processes more daily transactions than Ethereum for at least 30 consecutive days before December 31, 2025.",
      probability: 35,
      volume: "$9,200",
      endDate: "2025-12-31",
      category: "Crypto",
      isResolved: false,
      change: 7,
      traders: 103,
      resolutionDetails: "Resolution will be based on transaction data from blockchain explorers and analytics platforms like Etherscan and Solana Beach.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will ISRO successfully launch the Gaganyaan mission with humans by 2025?",
      description: "This market resolves to YES if the Indian Space Research Organisation (ISRO) successfully launches the Gaganyaan mission with human astronauts by December 31, 2025.",
      probability: 58,
      volume: "$6,800",
      endDate: "2025-12-31",
      category: "Science",
      isResolved: false,
      change: 2,
      traders: 91,
      resolutionDetails: "Resolution will be based on official announcements from ISRO and successful completion of the mission with humans returning safely to Earth.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Reliance Industries become a $500 billion company by market cap in 2025?",
      description: "This market resolves to YES if Reliance Industries' market capitalization reaches or exceeds $500 billion USD at any point during 2025.",
      probability: 45,
      volume: "$8,100",
      endDate: "2025-12-31",
      category: "Economics",
      isResolved: false,
      change: -3,
      traders: 76,
      resolutionDetails: "Resolution will be based on market capitalization data from major stock exchanges and financial data providers.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India and Pakistan play a bilateral cricket series by end of 2025?",
      description: "This market resolves to YES if India and Pakistan play an official bilateral cricket series (Test, ODI, or T20I) by December 31, 2025.",
      probability: 20,
      volume: "$14,500",
      endDate: "2025-12-31",
      category: "Sports",
      isResolved: false,
      change: 1,
      traders: 187,
      resolutionDetails: "Resolution will be based on official announcements and fixtures from the BCCI, PCB, and ICC.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will a quantum computer break RSA-2048 encryption by end of 2026?",
      description: "This market resolves to YES if a quantum computer successfully breaks RSA-2048 encryption by December 31, 2026.",
      probability: 12,
      volume: "$5,300",
      endDate: "2026-12-31",
      category: "Science",
      isResolved: false,
      change: -2,
      traders: 68,
      resolutionDetails: "Resolution will be based on peer-reviewed scientific publications and verification by cryptography experts.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will the BJP win more than 300 seats in the 2024 Lok Sabha elections?",
      description: "This market resolves to YES if the Bharatiya Janata Party (BJP) wins more than 300 seats in the 2024 Lok Sabha elections.",
      probability: 60,
      volume: "$16,700",
      endDate: "2024-06-30",
      category: "Politics",
      isResolved: false,
      change: -5,
      traders: 245,
      resolutionDetails: "Resolution will be based on the official election results as announced by the Election Commission of India.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Virat Kohli score more than 75 international centuries by end of 2025?",
      description: "This market resolves to YES if Virat Kohli's total international centuries (Test, ODI, and T20I combined) exceeds 75 by December 31, 2025.",
      probability: 68,
      volume: "$9,800",
      endDate: "2025-12-31",
      category: "Sports",
      isResolved: false,
      change: 4,
      traders: 132,
      resolutionDetails: "Resolution will be based on official cricket statistics as maintained by the ICC and cricket boards.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India's GDP growth exceed 8% in fiscal year 2024-25?",
      description: "This market resolves to YES if India's GDP growth rate for the fiscal year 2024-25 exceeds 8% as per official government data.",
      probability: 52,
      volume: "$7,300",
      endDate: "2025-06-30",
      category: "Economics",
      isResolved: false,
      change: 3,
      traders: 84,
      resolutionDetails: "Resolution will be based on official GDP data released by the Ministry of Statistics and Programme Implementation, Government of India.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will a Bollywood film win an Oscar by 2026?",
      description: "This market resolves to YES if any Bollywood film wins an Academy Award (Oscar) in any category by the 2026 ceremony.",
      probability: 15,
      volume: "$4,200",
      endDate: "2026-03-31",
      category: "Entertainment",
      isResolved: false,
      change: 1,
      traders: 73,
      resolutionDetails: "Resolution will be based on the official results of the Academy Awards ceremonies up to and including 2026.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will the Sensex cross 100,000 points by end of 2025?",
      description: "This market resolves to YES if the BSE Sensex index crosses 100,000 points at any point before December 31, 2025.",
      probability: 40,
      volume: "$11,500",
      endDate: "2025-12-31",
      category: "Economics",
      isResolved: false,
      change: 6,
      traders: 156,
      resolutionDetails: "Resolution will be based on official BSE Sensex data as reported by the Bombay Stock Exchange.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Cardano (ADA) reach $10 by end of 2025?",
      description: "This market resolves to YES if the price of Cardano (ADA) reaches or exceeds $10 USD on any major exchange before January 1, 2026.",
      probability: 28,
      volume: "$6,700",
      endDate: "2025-12-31",
      category: "Crypto",
      isResolved: false,
      change: 4,
      traders: 92,
      resolutionDetails: "Resolution will be based on the price data from at least three major cryptocurrency exchanges.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India implement a Uniform Civil Code by end of 2025?",
      description: "This market resolves to YES if the Government of India implements a nationwide Uniform Civil Code by December 31, 2025.",
      probability: 55,
      volume: "$8,900",
      endDate: "2025-12-31",
      category: "Politics",
      isResolved: false,
      change: 7,
      traders: 118,
      resolutionDetails: "Resolution will be based on official legislation passed by the Parliament of India and implemented by the government.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will a self-driving car service operate commercially in at least 5 Indian cities by 2026?",
      description: "This market resolves to YES if a commercial self-driving car service (Level 4 or higher autonomy) operates in at least 5 major Indian cities by December 31, 2026.",
      probability: 22,
      volume: "$5,100",
      endDate: "2026-12-31",
      category: "Science",
      isResolved: false,
      change: 2,
      traders: 64,
      resolutionDetails: "Resolution will be based on verifiable commercial operations of self-driving car services in Indian cities.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Mukesh Ambani become the world's richest person by end of 2025?",
      description: "This market resolves to YES if Mukesh Ambani becomes the world's richest person according to Forbes or Bloomberg Billionaires Index at any point before December 31, 2025.",
      probability: 18,
      volume: "$10,200",
      endDate: "2025-12-31",
      category: "Economics",
      isResolved: false,
      change: 3,
      traders: 143,
      resolutionDetails: "Resolution will be based on the Forbes Real-Time Billionaires List or Bloomberg Billionaires Index.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India host the FIFA World Cup by 2030?",
      description: "This market resolves to YES if India is selected as the host (or co-host) for the FIFA World Cup to be held by 2030.",
      probability: 10,
      volume: "$4,800",
      endDate: "2026-12-31",
      category: "Sports",
      isResolved: false,
      change: 1,
      traders: 87,
      resolutionDetails: "Resolution will be based on official announcements from FIFA regarding World Cup host selections.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Ripple (XRP) win its case against the SEC and reach $5 by end of 2024?",
      description: "This market resolves to YES if Ripple wins its case against the SEC and XRP reaches a price of $5 or higher on major exchanges by December 31, 2024.",
      probability: 32,
      volume: "$7,600",
      endDate: "2024-12-31",
      category: "Crypto",
      isResolved: false,
      change: 9,
      traders: 108,
      resolutionDetails: "Resolution will be based on the final court decision and price data from major cryptocurrency exchanges.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India achieve its target of 500 GW renewable energy capacity by 2030?",
      description: "This market resolves to YES if India achieves its target of 500 GW of renewable energy capacity by December 31, 2030.",
      probability: 45,
      volume: "$6,300",
      endDate: "2030-12-31",
      category: "Science",
      isResolved: false,
      change: 2,
      traders: 76,
      resolutionDetails: "Resolution will be based on official data from the Ministry of New and Renewable Energy, Government of India.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Rahul Gandhi become Prime Minister of India by 2029?",
      description: "This market resolves to YES if Rahul Gandhi becomes the Prime Minister of India at any point before December 31, 2029.",
      probability: 25,
      volume: "$13,700",
      endDate: "2029-12-31",
      category: "Politics",
      isResolved: false,
      change: -3,
      traders: 196,
      resolutionDetails: "Resolution will be based on official government announcements and swearing-in ceremonies.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will the Indian rupee strengthen to below 70 per USD by end of 2025?",
      description: "This market resolves to YES if the exchange rate of Indian Rupee strengthens to below 70 per US Dollar for at least 30 consecutive days before December 31, 2025.",
      probability: 20,
      volume: "$8,400",
      endDate: "2025-12-31",
      category: "Economics",
      isResolved: false,
      change: -2,
      traders: 112,
      resolutionDetails: "Resolution will be based on official exchange rate data from the Reserve Bank of India and major forex markets.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India win the T20 World Cup in 2026?",
      description: "This market resolves to YES if the Indian cricket team wins the ICC T20 World Cup scheduled to be held in 2026.",
      probability: 38,
      volume: "$9,700",
      endDate: "2026-12-31",
      category: "Sports",
      isResolved: false,
      change: 5,
      traders: 167,
      resolutionDetails: "Resolution will be based on the official results as declared by the International Cricket Council (ICC).",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Polygon (MATIC) reach $10 by end of 2025?",
      description: "This market resolves to YES if the price of Polygon (MATIC) reaches or exceeds $10 USD on any major exchange before January 1, 2026.",
      probability: 42,
      volume: "$5,900",
      endDate: "2025-12-31",
      category: "Crypto",
      isResolved: false,
      change: 8,
      traders: 83,
      resolutionDetails: "Resolution will be based on the price data from at least three major cryptocurrency exchanges.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India's first bullet train project be fully operational by end of 2026?",
      description: "This market resolves to YES if India's first bullet train project (Mumbai-Ahmedabad High-Speed Rail Corridor) becomes fully operational by December 31, 2026.",
      probability: 60,
      volume: "$7,200",
      endDate: "2026-12-31",
      category: "Science",
      isResolved: false,
      change: 4,
      traders: 95,
      resolutionDetails: "Resolution will be based on official announcements from the National High Speed Rail Corporation Limited (NHSRCL) and the Ministry of Railways.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will the Congress party win more than 150 seats in the 2024 Lok Sabha elections?",
      description: "This market resolves to YES if the Indian National Congress wins more than 150 seats in the 2024 Lok Sabha elections.",
      probability: 35,
      volume: "$12,800",
      endDate: "2024-06-30",
      category: "Politics",
      isResolved: false,
      change: 6,
      traders: 178,
      resolutionDetails: "Resolution will be based on the official election results as announced by the Election Commission of India.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will an Indian startup achieve unicorn status with a valuation over $10 billion by 2025?",
      description: "This market resolves to YES if any Indian startup achieves a valuation of over $10 billion by December 31, 2025.",
      probability: 65,
      volume: "$6,500",
      endDate: "2025-12-31",
      category: "Economics",
      isResolved: false,
      change: 7,
      traders: 89,
      resolutionDetails: "Resolution will be based on funding rounds, IPOs, or acquisitions that value the startup at over $10 billion, as reported by reliable financial news sources.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Shah Rukh Khan win a National Film Award for Best Actor by 2026?",
      description: "This market resolves to YES if Shah Rukh Khan wins the National Film Award for Best Actor for any film by December 31, 2026.",
      probability: 30,
      volume: "$4,300",
      endDate: "2026-12-31",
      category: "Entertainment",
      isResolved: false,
      change: 2,
      traders: 71,
      resolutionDetails: "Resolution will be based on the official announcements of National Film Awards by the Directorate of Film Festivals, Government of India.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India achieve a medal tally of 20+ at the 2028 Olympics?",
      description: "This market resolves to YES if India wins 20 or more medals (gold, silver, and bronze combined) at the 2028 Summer Olympics in Los Angeles.",
      probability: 48,
      volume: "$8,100",
      endDate: "2028-08-31",
      category: "Sports",
      isResolved: false,
      change: 5,
      traders: 103,
      resolutionDetails: "Resolution will be based on the official medal count as declared by the International Olympic Committee at the conclusion of the 2028 Summer Olympics.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Shiba Inu (SHIB) reach $0.001 by end of 2025?",
      description: "This market resolves to YES if the price of Shiba Inu (SHIB) reaches or exceeds $0.001 USD on any major exchange before January 1, 2026.",
      probability: 15,
      volume: "$6,800",
      endDate: "2025-12-31",
      category: "Crypto",
      isResolved: false,
      change: 3,
      traders: 97,
      resolutionDetails: "Resolution will be based on the price data from at least three major cryptocurrency exchanges.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India successfully test a hypersonic missile by end of 2025?",
      description: "This market resolves to YES if India successfully tests a hypersonic missile (speed of Mach 5 or higher) by December 31, 2025.",
      probability: 70,
      volume: "$5,400",
      endDate: "2025-12-31",
      category: "Science",
      isResolved: false,
      change: 4,
      traders: 82,
      resolutionDetails: "Resolution will be based on official announcements from the Defence Research and Development Organisation (DRDO) or Ministry of Defence.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Article 370 be reinstated in Jammu and Kashmir by 2026?",
      description: "This market resolves to YES if Article 370 is reinstated in Jammu and Kashmir by December 31, 2026.",
      probability: 12,
      volume: "$11,200",
      endDate: "2026-12-31",
      category: "Politics",
      isResolved: false,
      change: -1,
      traders: 165,
      resolutionDetails: "Resolution will be based on official constitutional amendments or Supreme Court judgments regarding Article 370.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India's retail inflation remain below 5% throughout 2025?",
      description: "This market resolves to YES if India's retail inflation, as measured by the Consumer Price Index (CPI), remains below 5% for all months of 2025.",
      probability: 40,
      volume: "$6,100",
      endDate: "2025-12-31",
      category: "Economics",
      isResolved: false,
      change: 2,
      traders: 74,
      resolutionDetails: "Resolution will be based on monthly inflation data published by the Ministry of Statistics and Programme Implementation, Government of India.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will MS Dhoni play in IPL 2025?",
      description: "This market resolves to YES if MS Dhoni plays at least one match in the Indian Premier League (IPL) 2025 season.",
      probability: 45,
      volume: "$13,500",
      endDate: "2025-06-30",
      category: "Sports",
      isResolved: false,
      change: -4,
      traders: 221,
      resolutionDetails: "Resolution will be based on official IPL team announcements and match participation.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will Dogecoin (DOGE) reach $1 by end of 2025?",
      description: "This market resolves to YES if the price of Dogecoin (DOGE) reaches or exceeds $1 USD on any major exchange before January 1, 2026.",
      probability: 22,
      volume: "$8,700",
      endDate: "2025-12-31",
      category: "Crypto",
      isResolved: false,
      change: 5,
      traders: 114,
      resolutionDetails: "Resolution will be based on the price data from at least three major cryptocurrency exchanges.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will ISRO land a rover on the Moon's south pole by end of 2026?",
      description: "This market resolves to YES if the Indian Space Research Organisation (ISRO) successfully lands a rover on the Moon's south pole by December 31, 2026.",
      probability: 75,
      volume: "$7,300",
      endDate: "2026-12-31",
      category: "Science",
      isResolved: false,
      change: 8,
      traders: 98,
      resolutionDetails: "Resolution will be based on official announcements from ISRO and successful landing and operation of the rover on the lunar south pole.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India implement a two-child policy by 2027?",
      description: "This market resolves to YES if the Government of India implements a nationwide two-child policy by December 31, 2027.",
      probability: 28,
      volume: "$9,400",
      endDate: "2027-12-31",
      category: "Politics",
      isResolved: false,
      change: 3,
      traders: 126,
      resolutionDetails: "Resolution will be based on official legislation passed by the Parliament of India and implemented by the government.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will the Indian rupee become fully convertible on capital account by 2026?",
      description: "This market resolves to YES if the Indian rupee becomes fully convertible on capital account by December 31, 2026.",
      probability: 35,
      volume: "$5,800",
      endDate: "2026-12-31",
      category: "Economics",
      isResolved: false,
      change: 4,
      traders: 81,
      resolutionDetails: "Resolution will be based on official announcements from the Reserve Bank of India and the Ministry of Finance.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will an Indian win a singles Grand Slam tennis title by 2027?",
      description: "This market resolves to YES if any Indian tennis player wins a singles Grand Slam title (Australian Open, French Open, Wimbledon, or US Open) by December 31, 2027.",
      probability: 8,
      volume: "$4,600",
      endDate: "2027-12-31",
      category: "Sports",
      isResolved: false,
      change: 1,
      traders: 69,
      resolutionDetails: "Resolution will be based on the official results of Grand Slam tournaments as declared by their respective organizing bodies.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will a central bank digital currency (CBDC) replace 25% of physical cash in India by 2026?",
      description: "This market resolves to YES if India's central bank digital currency (CBDC) replaces 25% or more of physical cash in circulation by December 31, 2026.",
      probability: 32,
      volume: "$7,900",
      endDate: "2026-12-31",
      category: "Crypto",
      isResolved: false,
      change: 6,
      traders: 88,
      resolutionDetails: "Resolution will be based on official data from the Reserve Bank of India regarding CBDC adoption and physical cash in circulation.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India achieve 100% electric vehicle sales for new passenger cars by 2030?",
      description: "This market resolves to YES if 100% of new passenger car sales in India are electric vehicles by December 31, 2030.",
      probability: 18,
      volume: "$6,400",
      endDate: "2030-12-31",
      category: "Science",
      isResolved: false,
      change: 2,
      traders: 79,
      resolutionDetails: "Resolution will be based on official vehicle registration data from the Ministry of Road Transport and Highways, Government of India.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India become a permanent member of the UN Security Council by 2028?",
      description: "This market resolves to YES if India becomes a permanent member of the United Nations Security Council by December 31, 2028.",
      probability: 25,
      volume: "$10,300",
      endDate: "2028-12-31",
      category: "Politics",
      isResolved: false,
      change: 3,
      traders: 142,
      resolutionDetails: "Resolution will be based on official announcements from the United Nations regarding Security Council reforms and membership.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      title: "Will India's GDP surpass Japan to become the world's third-largest economy by 2027?",
      description: "This market resolves to YES if India's nominal GDP surpasses Japan's to become the world's third-largest economy by December 31, 2027.",
      probability: 58,
      volume: "$9,100",
      endDate: "2027-12-31",
      category: "Economics",
      isResolved: false,
      change: 7,
      traders: 124,
      resolutionDetails: "Resolution will be based on GDP data from the World Bank, International Monetary Fund, or other recognized international financial institutions.",
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ];
  
  const insertMarkets = async () => {
    let client;
    try {
      // Connect to MongoDB
      const uri = process.env.MONGODB_URI || "mongodb+srv://helloworldabaa:ULw4tqFta92Mba4@cluster0.dq5ts.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0";
      client = new MongoClient(uri);
      
      await client.connect();
      console.log("Connected to MongoDB");
      
      const database = client.db(); // Use the database from your connection string
      const marketsCollection = database.collection("markets");
      
      // Insert the data
      const result = await marketsCollection.insertMany(marketData);
      console.log(`${result.insertedCount} markets were inserted`);
      
    } catch (error) {
      console.error("Error inserting markets:", error);
    } finally {
      if (client) {
        await client.close();
        console.log("MongoDB connection closed");
      }
    }
  };
  
  // Run the function
  insertMarkets();